runtime: nodejs20
env: standard

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
  - url: /static
    static_dir: public
    secure: always

  - url: /.*
    script: auto
    secure: always

env_variables:
  NODE_ENV: "production"
